ISAD251CafeApplication/Controllers/OrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISAD251CafeApplication.Models;
using ISAD251CafeApplication.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ISAD251CafeApplication.Models.ViewModels;

namespace ISAD251CafeApplication.Controllers
{
    public class OrderHistoryController : Controller
    {
        private readonly StoreContext _context;

        public OrderHistoryController(StoreContext context)
        {
            _context = context;
        }

        [ActionName("Index")]
        [Route("[controller]")]
        public IActionResult Index()
        {

            
            List<Orders> orders = ManageCookies.GetOrdersFromCookies(Request.Cookies["orders"], _context);
            orders = orders.OrderByDescending(x => x.Created).ToList();

            orders = ManageOrderLines.Build(orders, _context);

            return View(orders);
        }

        [Route("[controller]/{id}")]
        public IActionResult Index(int id)
        {
            List<Orders> orders = new List<Orders>();
            Orders orderSingle = new Orders();

            orderSingle = _context.Orders.Find(id);

            if (orderSingle != null)
            {
                orders.Add(orderSingle);
                orders = ManageOrderLines.Build(orders, _context);
            }

            return View(orders);
     
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public IActionResult Cancel(int orderId)
        {
            Orders order = _context.Orders.Find(orderId);
            order.Cancelled = DateTime.Now;

            _context.Entry(order).State = EntityState.Modified;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ISAD251CafeApplication/Views/OrderHistory/Index.cshtml
@model IEnumerable<ISAD251CafeApplication.Models.Orders>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        $("#frmOrderSearch").submit(function () {
            var url = "OrderHistory/" + document.getElementById("txtSearch").value
            window.location.href = url;
        });
    });
</script>


<div class="panel panel-default" style="opacity:0.95; margin:50px;">
    <div class="panel-heading">
        All Orders
    </div>
    <div class="panel-body">

        <form id="frmOrderSearch" onsubmit="return false">
            <div class="row">
                <div class="col-sm-3">
                    <input type="text" class="form-control" id="txtSearch" placeholder="Search By Order ID" />
                </div>
                <div class="col-sm-2">
                    <input type="submit" id="btnSearch" class="btn btn-primary" value="Search" />
                </div>
            </div>
        </form>
        <hr />

        @{
            if (Model != null && Model.Count() > 0)
            {

                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.OrderId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TableNumber)
                            </th>
                            <th>
                                Order Content
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TotalPrice)
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Created)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var order in Model)
                        {
                            string status = "";
                            DateTime? statusDateTime = null;

                            if (order.Cancelled != null)
                            {
                                status = "Cancelled";
                                statusDateTime = order.Cancelled;
                            }
                            else if (order.Completed != null)
                            {
                                status = "Completed";
                                statusDateTime = order.Completed;
                            }
                            else
                            {
                                status = "Active";
                            }

                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => order.OrderId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => order.TableNumber)
                                </td>
                                <td>

                                    @{
                                        foreach (OrderLines ol in order.OrderLines)
                                        {

                                            <ul>
                                                <li>@ol.ItemName x @ol.Quantity = @Math.Round((ol.Quantity * ol.UnitPrice), 2) </li>
                                            </ul>
                                        }

                                    }

                                </td>
                                <td>
                                    &pound;@Html.DisplayFor(modelItem => order.TotalPrice)
                                </td>
                                <td>
                                    @status <br /> @statusDateTime
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => order.Created)
                                </td>
                                <td>
                                    @{
                                        @if (status == "Active")
                                        {
                                            using (Html.BeginForm("Cancel", "OrderHistory", FormMethod.Post))
                                            {
                                                <input type="hidden" name="orderId" value="@order.OrderId" />
                                                <input type="submit" class="btn btn-danger" value="Cancel Order" />
                                            }
                                        }
                                    }

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <h1>No Orders Found</h1>
                <p>No orders match your search criteria </p>
                <a href="/OrderHistory" role="button" class="btn btn-primary">Back to Order History</a>
            }
        }

    </div>

</div>