ISAD251CafeApplication/Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISAD251CafeApplication.Models;
using ISAD251CafeApplication.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ISAD251CafeApplication.Controllers.Admin
{
    public class AdminController : Controller
    {
        private readonly StoreContext _context;

        public AdminController(StoreContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Orders> orders = new List<Orders>();

            //TODO Investigate. OpenOrders doesn't seem to return view results
            //Brings back all results unless Linq filtered here.

            orders = _context.OpenOrders.Where(x=> x.Cancelled == null && x.Completed == null)
                                        .OrderBy(x => x.Created)
                                        .ToList();


            orders = ManageOrderLines.Build(orders, _context);

            return View(orders);
        }

        public IActionResult OrderComplete(int id)
        {
            Orders order = _context.Orders.Find(id);
            order.Completed = DateTime.Now;

            _context.Entry(order).State = EntityState.Modified;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

ISAD251CafeApplication/Controllers/Admin/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISAD251CafeApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ISAD251CafeApplication.Controllers.Admin
{
    public class ItemsController : Controller
    {
        private readonly StoreContext _context;

        public ItemsController(StoreContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Items.OrderBy(x => x.ItemCategory));
        }

        [Route("[controller]/{term}")]
        public IActionResult Index(string term)
        {
            List<Items> results = new List<Items>();

            try
            {
                int id = Convert.ToInt32(term);
                List<Items> idResults = _context.Items.Where(x => x.ItemId == id).ToList();
                results = idResults;
            }
            catch (FormatException)
            {
                //if entered value not an integer, search for the string in item name

                List<Items> nameResults =_context.Items.Where(x => x.ItemName.Contains(term)).ToList();
                results = nameResults;

                List<Items> descResults = _context.Items.Where(x => x.ItemDescription.Contains(term)).ToList();

                foreach (Items item in descResults)
                {
                    results.Add(item);
                }

            }

            return View(results.Distinct());
        }

        [Route("[controller]/[action]")]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public IActionResult Create([Bind("ItemId,ItemCategory,ItemName,ItemDescription,ItemPrice,ItemStock,Active")] Items newItem)
        {
            
            _context.Entry(newItem).State = EntityState.Added;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id) 
        {
            return View(_context.Items.Find(id));
        }

        [HttpPost]
        public ActionResult Edit([Bind("ItemId,ItemCategory,ItemName,ItemDescription,ItemPrice,ItemStock,Active, Created")] Items updatedItem)
        {
           if (ModelState.IsValid)
            {

                _context.Entry(updatedItem).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// A method to toggle the status of an item/product. If current on sale will be removed, 
        /// and vice versa
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult ToggleMenuStatus(int id)
        {
            Items item = _context.Items.Find(id);
            item.Active = !item.Active;

            _context.Entry(item).State = EntityState.Modified;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ISAD251CafeApplication/Controllers/Admin/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISAD251CafeApplication.Models;
using ISAD251CafeApplication.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ISAD251CafeApplication.Controllers.Admin
{
    public class OrdersController : Controller
    {
        private readonly StoreContext _context;

        public OrdersController(StoreContext context)
        {
            _context = context;
        }
        [Route("[controller]")]
        public IActionResult Index()
        {
            List<Orders> orders = new List<Orders>();

            orders = _context.Orders.OrderByDescending(x => x.Created).ToList();

            orders = ManageOrderLines.Build(orders, _context);

            return View(orders);
        }

        [Route("[controller]/{id}")]
        public IActionResult Index(int id)
        {
            List<Orders> orders = new List<Orders>();
            Orders orderResult = _context.Orders.Find(id);

            if(orderResult != null)
            {
                orders.Add(_context.Orders.Find(id));
                orders = ManageOrderLines.Build(orders, _context);
            }

            return View(orders);
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public IActionResult OrderComplete(int orderId, string caller)
        {

            Orders order = _context.Orders.Find(orderId);
            order.Completed = DateTime.Now;

            _context.Entry(order).State = EntityState.Modified;
            _context.SaveChanges();

            if(caller == "orders")
            {
                return RedirectToAction("Index");
            }

                return RedirectToAction("Index", "Admin");

            
        }
    }
}

ISAD251CafeApplication/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISAD251CafeApplication.Helpers;
using ISAD251CafeApplication.Models;
using ISAD251CafeApplication.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ISAD251CafeApplication.Controllers
{
    public class MenuController : Controller
    {
        private readonly StoreContext _context;

        public MenuController(StoreContext context)
        {
            _context = context;
        }

        [Route("[controller]")]
        public IActionResult Index()
        {

            //TODO Investigate. Menu doesn't seem to return view results
            //Brings back all results unless Linq filtered here.
            List<Items> basket = GetBasketAsList();
            List<Items> menuItems = _context.Menu.Where(x => x.Active == true)
                                                    .OrderBy(x => x.ItemCategory)
                                                    .ToList();

            MenuAndBasketViewModel model = new MenuAndBasketViewModel();
            model.Menu = menuItems;
            model.BasketPreview = ConvertToOrderLines(basket);
            ManageOrderLines.PopulateItemNames( model.BasketPreview, _context);

            return View(model);
        }

        [HttpPost]
        [Route("[controller]")]
        public IActionResult AddBasket(int itemId)
        {
            //ensure item added to basket exists 
            if (_context.Menu.Find(itemId) != null)
            {
                List<Items> basket = GetBasketAsList();
                if (_context.Menu.Find(itemId) != null)
                {
                    basket.Add(_context.Menu.Find(itemId));
                }
                
                SetBasketInSession(basket);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveItem(int itemId)
        {
            List<Items> items = GetBasketAsList();
            
            foreach (Items item in items.ToList())
            {
                if(item.ItemId == itemId)
                {
                    items.Remove(item);
                }
            }

            SetBasketInSession(items);

            return RedirectToAction("Index");

        }

        public IActionResult Checkout()
        {
            List<OrderLines> orderLines = ConvertToOrderLines(GetBasketAsList());
            ManageOrderLines.PopulateItemNames(orderLines, _context);
            return View(orderLines);
        }

        [Route("[controller]/[action]/{tableNumber}")]
        public IActionResult CompleteOrder(int tableNumber)
        {
            List<Items> basket = GetBasketAsList();
            HttpContext.Session.Clear();

            Orders order = new Orders(tableNumber, basket);
            order.OrderLines = ConvertToOrderLines(basket);
            ManageOrderLines.PopulateItemNames(ref order, _context);

            _context.Orders.Add(order);
            _context.SaveChanges();

            CookieOptions options = new CookieOptions();
            Response.Cookies.Append("orders",
                                   ManageCookies.AppendCookie(ref options, Request.Cookies["orders"], order.OrderId),
                                   options);



            return RedirectToAction("Index", "OrderHistory");           
        }



        private List<Items> GetBasketAsList()
        {
            List<Items> basket = new List<Items>();

            string sessionBasketString = HttpContext.Session.GetString("basket");

            if (!string.IsNullOrEmpty(sessionBasketString))
            {
                basket = JsonConvert.DeserializeObject<List<Items>>(sessionBasketString);
            }

            return basket;
        }

        private void SetBasketInSession(List<Items> basket)
        {
            HttpContext.Session.SetString("basket", JsonConvert.SerializeObject(basket));
        }

       
        
        /// <summary>
        /// Converts a List<Items> (shopping basket) to List of orderLines
        /// Ensures each item only listed once and allocates appropriate quantity.
        /// </summary>
        private List<OrderLines> ConvertToOrderLines(List<Items> basketObj)
        {

            List<OrderLines> orderLines = new List<OrderLines>();


            foreach (var item in basketObj)
            {
                OrderLines tempOrderLine = new OrderLines(item);
                bool itemAlreadyInList = false;

                if (orderLines.Count == 0)
                {
                    orderLines.Add(tempOrderLine);
                }
                else
                {
                    foreach (var ol in orderLines)
                    {
                        if (ol.ItemId == item.ItemId)
                        {
                            ol.Quantity++;
                            itemAlreadyInList = true;
                        }

                    }
                    if (!itemAlreadyInList)
                    {
                        orderLines.Add(new OrderLines(item));
                    }
                }
            }

            return orderLines;
        }
    }
}

ISAD251CafeApplication/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Added by N Harrington -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!---->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISAD Cafe Admin </title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ISAD Cafe Admin Panel</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Live Orders</a></li>
                    <li><a asp-area="" asp-controller="Orders" asp-action="Index">Order Data</a></li>
                    <li><a asp-area="" asp-controller="Items" asp-action="Index">Products</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()

        <footer>
            
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ISAD251CafeApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Added by N Harrington -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!---->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISAD Cafe</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ISAD Cafe</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Menu" asp-action="">Menu</a></li>
                    <li><a asp-area="" asp-controller="OrderHistory" asp-action="">Order History</a></li>
                    <li><a asp-area="" asp-controller="Privacy" asp-action="">Privacy</a></li>
                    <li><a asp-area="" asp-controller="Accessibility" asp-action="">Accessibility</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    @RenderBody()

    <footer>
    </footer>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>